services:
  #Postgres service running on Ubuntu.
  postgres_ubuntu:
    image: postgres:latest
    container_name: postgres_site
    environment:
      - POSTGRES_DB=distributed_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - distributed_network
  #MariaDB  service running on Ubuntu.
  mariadb_ubuntu:
    image: mariadb:latest
    container_name: mariadb_site
    environment:
      - MARIADB_DATABASE=distributed_db
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - distributed_network
  #SQLite service on Windows
  SQLite_windows:
    #Using windows server core as the base image
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    # Install SQLite and create database
    command:
      - powershell
      - |
        Invoke-WebRequest -Uri 'https://sqlite.org/2024/sqlite-tools-win32-x86-3430200.zip' -OutFile 'C:\sqlite.zip'
        Expand-Archive C:\sqlite.zip -DestinationPath C:\sqlite
        Set-Location C:\sqlite
        .\sqlite3.exe C:\sqlite_data\distributed_db.sqlite
    networks:
      - distributed_network
volumes:
  postgres_data:
  mariadb_data:
  sqlite_data:
networks:
  distributed_network:
    driver: bridge
