services:
  # Postgres for middleware
  postgres_middleware:
    image: postgres:latest
    container_name: postgres_middleware
    environment:
      - POSTGRES_DB=middleware_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      "7002:5432"
    volumes:
      - middleware_data:/var/lib/postgresql/data
    networks:
      - distributed_network
  # Postgres service running on linux
  # To use psql in the container run : docker exec -it postgres_site psql -U postgres
  postgres_ubuntu:
    image: postgres:latest
    container_name: postgres_site
    environment:
      - POSTGRES_DB=distributed_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "7000:5432" # Exposing container's port 5432 to host's port 7000
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - distributed_network

  # MariaDB service running on linux
  # To use MariaDB monitor in the container run: docker exec -it mariadb_site mariadb -u root -ppassword
  mariadb_ubuntu:
    image: mariadb:latest
    container_name: mariadb_site
    environment:
      - MARIADB_DATABASE=distributed_db
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=password
    ports:
      - "7001:3306" # Exposing container's port 3306 to host's port 7001
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - distributed_network

  # SQLite service on OSX(macOS) (using dockurr/macos)
  SQLite_OSX:
    image: dockurr/macos
    container_name: sqlite_site
    volumes:
      - sqlite_data:/data
    networks:
      - distributed_network
    working_dir: /data
    entrypoint: /bin/bash
    command: >
      -c "apt-get update &&
          apt-get install -y unzip &&
          wget https://sqlite.org/2024/sqlite-tools-linux-x64-3470200.zip &&
          unzip -u sqlite-tools-linux-x64-3470200.zip -d /usr/local/bin &&
          /usr/local/bin/sqlite3 /data/distributed_db.sqlite"

volumes:
  postgres_data:
  mariadb_data:
  sqlite_data:

networks:
  distributed_network:
    driver: bridge
